on:
 push:
   branches:
   - main
   paths:
   - '01_infraaaaaaaaaa/01-aws/aws/04_aws_upstream/terraform.tfvars'
   - '01_infraaaaaaaaaa/01-aws/aws/04_aws_upstream/gitops'

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
 GITHUB: ${{ secrets.GITHUB }}
 AWS_VELERO_01: ${{ secrets.VELERO01 }}
 AWS_VELERO_02: ${{ secrets.VELERO02 }}
 AWS_VELERO_03: ${{ secrets.VELERO03 }}

jobs:
 build:
   name: "test"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: 01_infra/01-upstream/aws/04_aws_upstream/
   steps:
     - name: test
       uses: actions/checkout@v3

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0
